DROP SEQUENCE ADMINLOGIN_SEQ;
DROP TABLE ADMINLOGIN CASCADE CONSTRAINTS;

CREATE TABLE ADMINLOGIN(LOGIN_ID NUMBER(3) PRIMARY KEY, USERNAME VARCHAR2(50),  PASSWORD VARCHAR2(30));

CREATE SEQUENCE ADMINLOGIN_SEQ START WITH 1 INCREMENT BY 1;