DROP SEQUENCE MOVIEPROJECT_SEQ;
DROP TABLE MOVIEPROJECT CASCADE CONSTRAINTS;

CREATE TABLE MOVIEPROJECT(MOVIE_ID NUMBER(3), MOVIE_NAME VARCHAR2(70), RATING NUMBER(4,2), GENRE VARCHAR2(100),QUALITY VARCHAR2(6), OVERVIEW VARCHAR2(1000), DURATION VARCHAR2(10), RELEASE_DATE DATE, IMAGE_PATH VARCHAR2(100), CONSTRAINT MOVIEPROJECT_CONS PRIMARY KEY(MOVIE_ID));

CREATE SEQUENCE MOVIEPROJECT_SEQ START WITH 1 INCREMENT BY 1;