DROP SEQUENCE USERLOGIN_SEQ;
DROP TABLE USERLOGIN CASCADE CONSTRAINTS;

CREATE TABLE USERLOGIN(LOGIN_ID NUMBER(3) PRIMARY KEY,EMAIL_ID VARCHAR2(50), PASSWORD VARCHAR2(30));

CREATE SEQUENCE USERLOGIN_SEQ START WITH 1 INCREMENT BY 1;