DROP SEQUENCE USER_SEQ;
DROP TABLE USERS CASCADE CONSTRAINTS;

CREATE TABLE USERS(USER_ID NUMBER(3) PRIMARY KEY, NAME VARCHAR2(40), EMAIL_ID VARCHAR2(50), PHONE_NUMBER NUMBER(12), USER_DOB DATE, LOGIN_ID NUMBER(3), FOREIGN KEY(LOGIN_ID) REFERENCES USERLOGIN(LOGIN_ID));

CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;
